name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Check Flutter & Dart
        run: flutter doctor -v

      - name: Get Dependencies
        run: flutter pub get

      - name: Analyze Dart Code (Diagnose compilation errors)
        run: flutter analyze

      - name: Build APK Debug
        run: flutter build apk --debug --verbose

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ZarinParseh-App
          path: build/app/outputs/flutter-apk/*.apk
